import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const RULES_FILE = join(__dirname, '..', 'data', 'learned-rules.json');

// ═══════════════════════════════════════════════════════════════════════════════
// FEEDBACK LEARNING SERVICE
//
// When a writer gives negative feedback (thumbs down + comment), this service:
//   1. Uses AI to convert the feedback into a concise, permanent rule
//   2. Saves the rule to learned-rules.json
//   3. Updates the in-memory rules cache
//
// The rules are loaded ONCE at startup and appended to every system prompt.
// No per-call DB queries — the learning is permanent and instant.
// ═══════════════════════════════════════════════════════════════════════════════

// In-memory cache of learned rules — loaded once at startup
let _learnedRules = [];
let _rulesPromptCache = '';

/**
 * Load rules from disk into memory. Called once at startup.
 */
function loadRules() {
  try {
    if (existsSync(RULES_FILE)) {
      const raw = readFileSync(RULES_FILE, 'utf-8');
      _learnedRules = JSON.parse(raw);
      _rebuildPromptCache();
      console.log(`📘 [Feedback Learning] Loaded ${_learnedRules.length} learned rules from disk`);
    } else {
      _learnedRules = [];
      _rulesPromptCache = '';
      console.log('📘 [Feedback Learning] No learned-rules.json found — starting fresh');
    }
  } catch (e) {
    console.warn('[Feedback Learning] Failed to load rules:', e.message);
    _learnedRules = [];
    _rulesPromptCache = '';
  }
}

/**
 * Save current rules to disk.
 */
function saveRules() {
  try {
    writeFileSync(RULES_FILE, JSON.stringify(_learnedRules, null, 2), 'utf-8');
  } catch (e) {
    console.error('[Feedback Learning] Failed to save rules:', e.message);
  }
}

/**
 * Rebuild the prompt text cache from current rules.
 */
function _rebuildPromptCache() {
  if (_learnedRules.length === 0) {
    _rulesPromptCache = '';
    return;
  }

  const ruleLines = _learnedRules.map((r, i) => `${i + 1}. ${r.rule}`).join('\n');

  _rulesPromptCache = `\n\n═══ LEARNED RULES FROM WRITER FEEDBACK ═══
Writers have flagged the following issues in past responses. These are PERMANENT rules — follow them in EVERY response:

${ruleLines}

Apply ALL of these rules. They represent real corrections from the content writing team.
═══ END LEARNED RULES ═══`;
}

/**
 * Get the prompt text for learned rules (appended to system prompt).
 * Returns empty string if no rules exist.
 */
export function getLearnedRulesPrompt() {
  return _rulesPromptCache;
}

/**
 * Add a new learned rule from negative feedback.
 * The rule is generated by AI from the feedback context.
 * @param {object} params
 * @param {string} params.comment - Writer's feedback comment
 * @param {string} params.userMessage - What the writer asked
 * @param {string} params.assistantResponse - What the agent responded
 * @param {string} params.toolsUsed - Tools used in the response
 * @param {string} params.topic - Article topic
 */
export async function addLearnedRule({ comment, userMessage, assistantResponse, toolsUsed, topic }) {
  if (!comment || comment.trim().length < 3) return null;

  // Generate a concise rule from the feedback using AI
  const rule = await generateRuleFromFeedback({ comment, userMessage, assistantResponse, toolsUsed, topic });
  if (!rule) return null;

  // Check for duplicate/similar rules
  const isDuplicate = _learnedRules.some(r => {
    const existing = r.rule.toLowerCase();
    const newRule = rule.toLowerCase();
    // Simple word overlap check
    const existingWords = new Set(existing.split(/\s+/).filter(w => w.length > 3));
    const newWords = new Set(newRule.split(/\s+/).filter(w => w.length > 3));
    const overlap = [...newWords].filter(w => existingWords.has(w)).length;
    return overlap > Math.min(existingWords.size, newWords.size) * 0.6;
  });

  if (isDuplicate) {
    console.log('[Feedback Learning] Skipped duplicate rule');
    return null;
  }

  const entry = {
    rule,
    source: comment.substring(0, 200),
    topic: topic || '',
    createdAt: new Date().toISOString()
  };

  _learnedRules.push(entry);

  // Keep max 30 rules — remove oldest if exceeded
  if (_learnedRules.length > 30) {
    _learnedRules = _learnedRules.slice(-30);
  }

  saveRules();
  _rebuildPromptCache();

  console.log(`📘 [Feedback Learning] New rule added: "${rule.substring(0, 80)}..." | Total rules: ${_learnedRules.length}`);
  return entry;
}

/**
 * Use AI to convert raw feedback into a concise, actionable rule.
 */
async function generateRuleFromFeedback({ comment, userMessage, assistantResponse, toolsUsed, topic }) {
  // Try to use whatever AI provider is available
  const openaiKey = process.env.OPENAI_API_KEY;
  const geminiKey = process.env.GEMINI_API_KEY;
  const anthropicKey = process.env.ANTHROPIC_API_KEY;

  const prompt = `You are a quality improvement system. A content writer gave negative feedback on an AI assistant's response. Convert this feedback into ONE concise rule (1-2 sentences max) that the AI should follow in ALL future responses.

Writer's feedback: "${comment}"
${userMessage ? `Writer asked: "${userMessage.substring(0, 300)}"` : ''}
${assistantResponse ? `AI responded: "${assistantResponse.substring(0, 400)}"` : ''}
${toolsUsed ? `Tools used: ${toolsUsed}` : ''}
${topic ? `Topic: ${topic}` : ''}

Output ONLY the rule — no explanation, no quotes, no numbering. The rule should be:
- Actionable and specific (not vague like "be better")
- Written as a direct instruction (e.g., "Always include..." or "Never use..." or "When asked about X, always...")
- Applicable to future responses on any topic (not just this specific one)

Examples of good rules:
- "Always include at least 3 specific CloudFuze features with technical details instead of vague capability descriptions."
- "When generating frameworks, include specific stats and data sources in each section guide — never leave sections without concrete data suggestions."
- "Never respond with generic cloud migration advice — always reference specific platforms (SharePoint, Google Drive, OneDrive) mentioned in the topic."`;

  try {
    if (openaiKey) {
      const { default: OpenAI } = await import('openai');
      const client = new OpenAI({ apiKey: openaiKey, timeout: 15000 });
      const resp = await client.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.2,
        max_tokens: 150
      });
      return (resp.choices[0]?.message?.content || '').trim();
    }

    if (geminiKey) {
      const { GoogleGenerativeAI } = await import('@google/generative-ai');
      const genAI = new GoogleGenerativeAI(geminiKey);
      const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
      const result = await model.generateContent(prompt);
      return (result.response.text() || '').trim();
    }

    if (anthropicKey) {
      const { default: Anthropic } = await import('@anthropic-ai/sdk');
      const client = new Anthropic({ apiKey: anthropicKey, timeout: 15000 });
      const resp = await client.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 150,
        messages: [{ role: 'user', content: prompt }]
      });
      return (resp.content[0]?.text || '').trim();
    }

    // No AI available — use the raw comment as the rule
    return `Based on writer feedback: ${comment.substring(0, 150)}`;
  } catch (e) {
    console.warn('[Feedback Learning] AI rule generation failed:', e.message);
    // Fallback: use the raw comment
    return `Based on writer feedback: ${comment.substring(0, 150)}`;
  }
}

/**
 * Get all current rules (for admin/debugging).
 */
export function getLearnedRules() {
  return [..._learnedRules];
}

/**
 * Remove a rule by index.
 */
export function removeLearnedRule(index) {
  if (index >= 0 && index < _learnedRules.length) {
    const removed = _learnedRules.splice(index, 1);
    saveRules();
    _rebuildPromptCache();
    return removed[0];
  }
  return null;
}

// ═══ LOAD RULES ON IMPORT ═══
loadRules();
