import { pool, query, one, rows, tx } from './pool.js';
import { dataPath } from '../config/paths.js';
import { existsSync } from 'fs';

// PostgreSQL-backed Copilot store (migrated from SQLite/better-sqlite3).
// All functions are async. Timestamps are stored as TEXT in the exact format
// SQLite's datetime('now') produced ('YYYY-MM-DD HH:MM:SS') so API responses
// and chronological ordering are unchanged. JSON fields stay TEXT and are
// (de)serialized in JS, matching the original behavior.

// Inline SQL expression that reproduces SQLite's datetime('now') (UTC, no TZ suffix).
const NOW = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')";

const SCHEMA = `
  CREATE TABLE IF NOT EXISTS writers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT DEFAULT '',
    created_at TEXT DEFAULT ${NOW}
  );

  CREATE TABLE IF NOT EXISTS articles (
    id TEXT PRIMARY KEY,
    writer_id TEXT NOT NULL REFERENCES writers(id),
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    url TEXT DEFAULT '',
    topic TEXT DEFAULT '',
    content_type TEXT DEFAULT 'general',
    primary_keyword TEXT DEFAULT '',
    secondary_keywords TEXT DEFAULT '[]',
    framework_used TEXT DEFAULT '[]',
    word_count INTEGER DEFAULT 0,
    published_at TEXT DEFAULT '',
    created_at TEXT DEFAULT ${NOW}
  );

  CREATE TABLE IF NOT EXISTS article_chunks (
    id TEXT PRIMARY KEY,
    article_id TEXT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    chunk_text TEXT NOT NULL,
    section_type TEXT DEFAULT '',
    heading TEXT DEFAULT '',
    chunk_index INTEGER DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS writer_profiles (
    writer_id TEXT PRIMARY KEY REFERENCES writers(id),
    avg_word_count REAL DEFAULT 0,
    preferred_frameworks TEXT DEFAULT '{}',
    common_topics TEXT DEFAULT '[]',
    writing_style TEXT DEFAULT '',
    tone_analysis TEXT DEFAULT '',
    total_articles INTEGER DEFAULT 0,
    updated_at TEXT DEFAULT ${NOW}
  );

  CREATE TABLE IF NOT EXISTS copilot_sessions (
    id TEXT PRIMARY KEY,
    writer_id TEXT NOT NULL REFERENCES writers(id),
    topic TEXT NOT NULL,
    content_type TEXT DEFAULT '',
    framework TEXT DEFAULT '[]',
    semantic_keywords TEXT DEFAULT '{}',
    current_content TEXT DEFAULT '',
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT ${NOW},
    updated_at TEXT DEFAULT ${NOW}
  );

  CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES copilot_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    tool_steps TEXT DEFAULT '[]',
    is_agent INTEGER DEFAULT 0,
    created_at TEXT DEFAULT ${NOW}
  );

  CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id);

  CREATE TABLE IF NOT EXISTS content_snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES copilot_sessions(id) ON DELETE CASCADE,
    content TEXT NOT NULL DEFAULT '',
    label TEXT DEFAULT '',
    source TEXT DEFAULT 'auto',
    word_count INTEGER DEFAULT 0,
    created_at TEXT DEFAULT ${NOW}
  );

  CREATE INDEX IF NOT EXISTS idx_content_snapshots_session ON content_snapshots(session_id);

  CREATE TABLE IF NOT EXISTS agent_feedback (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id TEXT NOT NULL,
    session_id TEXT DEFAULT '',
    writer_id TEXT DEFAULT '',
    score INTEGER NOT NULL,
    comment TEXT DEFAULT '',
    user_message TEXT DEFAULT '',
    assistant_response TEXT DEFAULT '',
    topic TEXT DEFAULT '',
    tools_used TEXT DEFAULT '',
    created_at TEXT DEFAULT ${NOW}
  );

  CREATE INDEX IF NOT EXISTS idx_agent_feedback_writer ON agent_feedback(writer_id);
  CREATE INDEX IF NOT EXISTS idx_agent_feedback_score ON agent_feedback(score);

  CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT DEFAULT ''
  );
`;

let initialized = null;

/** Create the schema, ensure the default writer, and auto-migrate legacy SQLite data once. */
export function initCopilotDb() {
  if (initialized) return initialized;
  initialized = (async () => {
    await query(SCHEMA);
    await query(
      "INSERT INTO writers (id, name, email) VALUES ('default', 'Default Writer', '') ON CONFLICT (id) DO NOTHING"
    );
    await maybeMigrateFromSqlite();
    console.log('  Copilot DB: PostgreSQL schema ready');
  })();
  return initialized;
}

// --- One-time auto-migration from the legacy copilot.db (better-sqlite3) ---

async function maybeMigrateFromSqlite() {
  const done = await one("SELECT value FROM schema_meta WHERE key = 'sqlite_migrated'");
  if (done) return;

  const legacyPath = dataPath('copilot.db');
  if (!existsSync(legacyPath)) {
    await query("INSERT INTO schema_meta (key, value) VALUES ('sqlite_migrated', 'no-legacy-file') ON CONFLICT (key) DO NOTHING");
    return;
  }

  console.log(`  Copilot DB: migrating legacy SQLite data from ${legacyPath} ...`);
  const { default: Database } = await import('better-sqlite3');
  const sqlite = new Database(legacyPath, { readonly: true });

  // (table, columns) — insert order respects foreign keys.
  const TABLES = [
    ['writers', ['id', 'name', 'email', 'created_at']],
    ['articles', ['id', 'writer_id', 'title', 'content', 'url', 'topic', 'content_type', 'primary_keyword', 'secondary_keywords', 'framework_used', 'word_count', 'published_at', 'created_at']],
    ['article_chunks', ['id', 'article_id', 'chunk_text', 'section_type', 'heading', 'chunk_index']],
    ['writer_profiles', ['writer_id', 'avg_word_count', 'preferred_frameworks', 'common_topics', 'writing_style', 'tone_analysis', 'total_articles', 'updated_at']],
    ['copilot_sessions', ['id', 'writer_id', 'topic', 'content_type', 'framework', 'semantic_keywords', 'current_content', 'status', 'created_at', 'updated_at']],
    ['chat_messages', ['id', 'session_id', 'role', 'content', 'tool_steps', 'is_agent', 'created_at']],
    ['content_snapshots', ['id', 'session_id', 'content', 'label', 'source', 'word_count', 'created_at']],
    ['agent_feedback', ['id', 'trace_id', 'session_id', 'writer_id', 'score', 'comment', 'user_message', 'assistant_response', 'topic', 'tools_used', 'created_at']],
  ];
  // Tables whose id is an IDENTITY column — bump the sequence after copying.
  const IDENTITY_TABLES = ['chat_messages', 'content_snapshots', 'agent_feedback'];

  try {
    let total = 0;
    await tx(async (client) => {
      for (const [table, cols] of TABLES) {
        let rowsToCopy = [];
        try {
          rowsToCopy = sqlite.prepare(`SELECT ${cols.join(', ')} FROM ${table}`).all();
        } catch (e) {
          continue; // table absent in legacy file — skip
        }
        const placeholders = cols.map((_, i) => `$${i + 1}`).join(', ');
        const sql = `INSERT INTO ${table} (${cols.join(', ')}) VALUES (${placeholders}) ON CONFLICT DO NOTHING`;
        for (const row of rowsToCopy) {
          await client.query(sql, cols.map(c => row[c]));
          total++;
        }
      }
      // Realign identity sequences so new inserts don't collide with copied ids.
      for (const table of IDENTITY_TABLES) {
        await client.query(
          `SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${table}), 0) + 1, false)`
        );
      }
      await client.query("INSERT INTO schema_meta (key, value) VALUES ('sqlite_migrated', $1) ON CONFLICT (key) DO NOTHING", [new Date().toISOString()]);
    });
    console.log(`  Copilot DB: migrated ${total} rows from legacy SQLite`);
  } finally {
    sqlite.close();
  }
}

// --- Writers ---

export async function getWriter(id) {
  return one('SELECT * FROM writers WHERE id = $1', [id]);
}

export async function createWriter(id, name, email = '') {
  await query('INSERT INTO writers (id, name, email) VALUES ($1, $2, $3) ON CONFLICT (id) DO NOTHING', [id, name, email]);
  return getWriter(id);
}

export async function listWriters() {
  return rows('SELECT * FROM writers ORDER BY created_at DESC');
}

// --- Articles ---

export async function saveArticle(article) {
  await query(
    `INSERT INTO articles (id, writer_id, title, content, url, topic, content_type, primary_keyword, secondary_keywords, framework_used, word_count, published_at, created_at)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, ${NOW})
     ON CONFLICT (id) DO UPDATE SET
       writer_id = excluded.writer_id, title = excluded.title, content = excluded.content,
       url = excluded.url, topic = excluded.topic, content_type = excluded.content_type,
       primary_keyword = excluded.primary_keyword, secondary_keywords = excluded.secondary_keywords,
       framework_used = excluded.framework_used, word_count = excluded.word_count,
       published_at = excluded.published_at, created_at = ${NOW}`,
    [
      article.id, article.writer_id, article.title, article.content,
      article.url || '', article.topic || '', article.content_type || 'general',
      article.primary_keyword || '',
      JSON.stringify(article.secondary_keywords || []),
      JSON.stringify(article.framework_used || []),
      article.word_count || 0,
      article.published_at || '',
    ]
  );
  return getArticle(article.id);
}

export async function getArticle(id) {
  const row = await one('SELECT * FROM articles WHERE id = $1', [id]);
  if (!row) return null;
  row.secondary_keywords = JSON.parse(row.secondary_keywords || '[]');
  row.framework_used = JSON.parse(row.framework_used || '[]');
  return row;
}

export async function listArticles(writerId, limit = 50) {
  return rows(
    'SELECT id, writer_id, title, topic, content_type, primary_keyword, word_count, published_at, created_at FROM articles WHERE writer_id = $1 ORDER BY created_at DESC LIMIT $2',
    [writerId, limit]
  );
}

export async function deleteArticle(id) {
  await query('DELETE FROM article_chunks WHERE article_id = $1', [id]);
  const res = await query('DELETE FROM articles WHERE id = $1', [id]);
  return res.rowCount > 0;
}

export async function searchArticles(writerId, q) {
  const pattern = `%${q}%`;
  return rows(
    'SELECT id, title, topic, content_type, primary_keyword, word_count, created_at FROM articles WHERE writer_id = $1 AND (title ILIKE $2 OR topic ILIKE $2 OR primary_keyword ILIKE $2 OR content ILIKE $2) ORDER BY created_at DESC LIMIT 20',
    [writerId, pattern]
  );
}

// --- Article Chunks ---

export async function saveChunks(articleId, chunks) {
  await tx(async (client) => {
    await client.query('DELETE FROM article_chunks WHERE article_id = $1', [articleId]);
    for (const c of chunks) {
      await client.query(
        'INSERT INTO article_chunks (id, article_id, chunk_text, section_type, heading, chunk_index) VALUES ($1, $2, $3, $4, $5, $6)',
        [c.id, articleId, c.chunk_text, c.section_type || '', c.heading || '', c.chunk_index || 0]
      );
    }
  });
}

export async function getChunks(articleId) {
  return rows('SELECT * FROM article_chunks WHERE article_id = $1 ORDER BY chunk_index', [articleId]);
}

export async function searchChunks(writerId, q, limit = 10) {
  const pattern = `%${q}%`;
  return rows(
    `SELECT ac.*, a.title as article_title, a.topic as article_topic
     FROM article_chunks ac
     JOIN articles a ON ac.article_id = a.id
     WHERE a.writer_id = $1 AND ac.chunk_text ILIKE $2
     ORDER BY a.created_at DESC
     LIMIT $3`,
    [writerId, pattern, limit]
  );
}

// --- Writer Profiles ---

export async function getWriterProfile(writerId) {
  const row = await one('SELECT * FROM writer_profiles WHERE writer_id = $1', [writerId]);
  if (!row) return null;
  row.preferred_frameworks = JSON.parse(row.preferred_frameworks || '{}');
  row.common_topics = JSON.parse(row.common_topics || '[]');
  return row;
}

export async function saveWriterProfile(profile) {
  await query(
    `INSERT INTO writer_profiles (writer_id, avg_word_count, preferred_frameworks, common_topics, writing_style, tone_analysis, total_articles, updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, $7, ${NOW})
     ON CONFLICT (writer_id) DO UPDATE SET
       avg_word_count = excluded.avg_word_count, preferred_frameworks = excluded.preferred_frameworks,
       common_topics = excluded.common_topics, writing_style = excluded.writing_style,
       tone_analysis = excluded.tone_analysis, total_articles = excluded.total_articles,
       updated_at = ${NOW}`,
    [
      profile.writer_id,
      profile.avg_word_count || 0,
      JSON.stringify(profile.preferred_frameworks || {}),
      JSON.stringify(profile.common_topics || []),
      profile.writing_style || '',
      profile.tone_analysis || '',
      profile.total_articles || 0,
    ]
  );
  return getWriterProfile(profile.writer_id);
}

// --- Copilot Sessions ---

export async function createSession(session) {
  await query(
    `INSERT INTO copilot_sessions (id, writer_id, topic, content_type, framework, semantic_keywords, current_content, status)
     VALUES ($1, $2, $3, $4, $5, $6, $7, 'active')`,
    [
      session.id, session.writer_id, session.topic,
      session.content_type || '',
      JSON.stringify(session.framework || []),
      JSON.stringify(session.semantic_keywords || {}),
      session.current_content || '',
    ]
  );
  return getSession(session.id);
}

export async function getSession(id) {
  const row = await one('SELECT * FROM copilot_sessions WHERE id = $1', [id]);
  if (!row) return null;
  row.framework = JSON.parse(row.framework || '[]');
  row.semantic_keywords = JSON.parse(row.semantic_keywords || '{}');
  return row;
}

export async function updateSession(id, updates) {
  const fields = [];
  const values = [];
  let n = 1;
  if (updates.current_content !== undefined) { fields.push(`current_content = $${n++}`); values.push(updates.current_content); }
  if (updates.framework !== undefined) { fields.push(`framework = $${n++}`); values.push(JSON.stringify(updates.framework)); }
  if (updates.semantic_keywords !== undefined) { fields.push(`semantic_keywords = $${n++}`); values.push(JSON.stringify(updates.semantic_keywords)); }
  if (updates.content_type !== undefined) { fields.push(`content_type = $${n++}`); values.push(updates.content_type); }
  if (updates.status !== undefined) { fields.push(`status = $${n++}`); values.push(updates.status); }
  if (fields.length === 0) return getSession(id);
  fields.push(`updated_at = ${NOW}`);
  values.push(id);
  await query(`UPDATE copilot_sessions SET ${fields.join(', ')} WHERE id = $${n}`, values);
  return getSession(id);
}

export async function listSessions(writerId, limit = 20) {
  return rows(
    'SELECT id, writer_id, topic, content_type, status, created_at, updated_at FROM copilot_sessions WHERE writer_id = $1 ORDER BY updated_at DESC LIMIT $2',
    [writerId, limit]
  );
}

// --- Content Snapshots ---

export async function saveContentSnapshot(sessionId, content, label = '', source = 'auto') {
  const wordCount = content.trim().split(/\s+/).filter(Boolean).length;
  await query(
    'INSERT INTO content_snapshots (session_id, content, label, source, word_count) VALUES ($1, $2, $3, $4, $5)',
    [sessionId, content, label, source, wordCount]
  );
}

export async function getContentSnapshots(sessionId) {
  return rows(
    'SELECT id, session_id, label, source, word_count, created_at FROM content_snapshots WHERE session_id = $1 ORDER BY created_at ASC',
    [sessionId]
  );
}

export async function getSnapshotContent(snapshotId) {
  return one('SELECT * FROM content_snapshots WHERE id = $1', [snapshotId]);
}

export async function deleteContentSnapshot(snapshotId) {
  const res = await query('DELETE FROM content_snapshots WHERE id = $1', [snapshotId]);
  return res.rowCount > 0;
}

// --- Chat Messages ---

export async function saveChatMessage(sessionId, role, content, toolSteps = [], isAgent = false) {
  await query(
    'INSERT INTO chat_messages (session_id, role, content, tool_steps, is_agent) VALUES ($1, $2, $3, $4, $5)',
    [sessionId, role, content, JSON.stringify(toolSteps), isAgent ? 1 : 0]
  );
}

export async function getSessionMessages(sessionId) {
  const result = await rows(
    'SELECT * FROM chat_messages WHERE session_id = $1 ORDER BY created_at ASC, id ASC',
    [sessionId]
  );
  return result.map(r => ({
    ...r,
    tool_steps: JSON.parse(r.tool_steps || '[]'),
    is_agent: !!r.is_agent,
  }));
}

export async function deleteSession(id) {
  await query('DELETE FROM chat_messages WHERE session_id = $1', [id]);
  await query('DELETE FROM content_snapshots WHERE session_id = $1', [id]);
  const res = await query('DELETE FROM copilot_sessions WHERE id = $1', [id]);
  return res.rowCount > 0;
}

// ═══ AGENT FEEDBACK ═══

export async function saveFeedback({ traceId, sessionId, writerId, score, comment, userMessage, assistantResponse, topic, toolsUsed }) {
  await query(
    'INSERT INTO agent_feedback (trace_id, session_id, writer_id, score, comment, user_message, assistant_response, topic, tools_used) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)',
    [
      traceId || '',
      sessionId || '',
      writerId || '',
      score,
      comment || '',
      (userMessage || '').substring(0, 2000),
      (assistantResponse || '').substring(0, 3000),
      topic || '',
      toolsUsed || '',
    ]
  );
}

/**
 * Get recent negative feedback for a writer (or all writers).
 * Used to inject "lessons learned" into the agent prompt so it avoids repeating mistakes.
 */
export async function getNegativeFeedback(writerId = '', limit = 10) {
  let sql = "SELECT comment, user_message, assistant_response, topic, tools_used, created_at FROM agent_feedback WHERE score = 0 AND comment != ''";
  const params = [];
  let n = 1;
  if (writerId) {
    sql += ` AND writer_id = $${n++}`;
    params.push(writerId);
  }
  sql += ` ORDER BY created_at DESC LIMIT $${n}`;
  params.push(limit);
  return rows(sql, params);
}

/** Get all feedback (positive + negative) for analytics. */
export async function getAllFeedback(limit = 50) {
  return rows('SELECT * FROM agent_feedback ORDER BY created_at DESC LIMIT $1', [limit]);
}

export default pool;
