import { pool, query, one, rows, tx } from './pool.js';
import { dataPath } from '../config/paths.js';
import { existsSync } from 'fs';

// PostgreSQL-backed email marketing store (migrated from SQLite/better-sqlite3).
// Shares the same Postgres database as copilotDb. All functions are async.
// Boolean-ish columns stay INTEGER (0/1) to match the original API shape.

const NOW = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')";

const SCHEMA = `
  CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT DEFAULT '',
    tags TEXT DEFAULT '',
    subscribed INTEGER DEFAULT 1,
    created_at TEXT DEFAULT ${NOW},
    updated_at TEXT DEFAULT ${NOW}
  );

  CREATE TABLE IF NOT EXISTS templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    html_body TEXT NOT NULL,
    created_at TEXT DEFAULT ${NOW},
    updated_at TEXT DEFAULT ${NOW}
  );

  CREATE TABLE IF NOT EXISTS campaigns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    html_body TEXT NOT NULL,
    template_id INTEGER,
    status TEXT DEFAULT 'draft',
    total_recipients INTEGER DEFAULT 0,
    sent_count INTEGER DEFAULT 0,
    open_count INTEGER DEFAULT 0,
    click_count INTEGER DEFAULT 0,
    scheduled_at TEXT,
    sent_at TEXT,
    created_at TEXT DEFAULT ${NOW},
    FOREIGN KEY (template_id) REFERENCES templates(id)
  );

  CREATE TABLE IF NOT EXISTS campaign_recipients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id INTEGER NOT NULL,
    contact_id INTEGER NOT NULL,
    tracking_id TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'pending',
    opened INTEGER DEFAULT 0,
    opened_at TEXT,
    clicked INTEGER DEFAULT 0,
    clicked_at TEXT,
    sent_at TEXT,
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_cr_campaign ON campaign_recipients(campaign_id);
  CREATE INDEX IF NOT EXISTS idx_cr_tracking ON campaign_recipients(tracking_id);
  CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);

  CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT DEFAULT ''
  );
`;

let initialized = null;

/** Create the email schema and auto-migrate legacy SQLite data once. */
export function initEmailDb() {
  if (initialized) return initialized;
  initialized = (async () => {
    await query(SCHEMA);
    await maybeMigrateFromSqlite();
    console.log('  Email DB: PostgreSQL schema ready');
  })();
  return initialized;
}

async function maybeMigrateFromSqlite() {
  const done = await one("SELECT value FROM schema_meta WHERE key = 'email_sqlite_migrated'");
  if (done) return;

  const legacyPath = dataPath('email.db');
  if (!existsSync(legacyPath)) {
    await query("INSERT INTO schema_meta (key, value) VALUES ('email_sqlite_migrated', 'no-legacy-file') ON CONFLICT (key) DO NOTHING");
    return;
  }

  console.log(`  Email DB: migrating legacy SQLite data from ${legacyPath} ...`);
  const { default: Database } = await import('better-sqlite3');
  const sqlite = new Database(legacyPath, { readonly: true });

  const TABLES = [
    ['contacts', ['id', 'email', 'name', 'tags', 'subscribed', 'created_at', 'updated_at']],
    ['templates', ['id', 'name', 'subject', 'html_body', 'created_at', 'updated_at']],
    ['campaigns', ['id', 'name', 'subject', 'html_body', 'template_id', 'status', 'total_recipients', 'sent_count', 'open_count', 'click_count', 'scheduled_at', 'sent_at', 'created_at']],
    ['campaign_recipients', ['id', 'campaign_id', 'contact_id', 'tracking_id', 'status', 'opened', 'opened_at', 'clicked', 'clicked_at', 'sent_at']],
  ];

  try {
    let total = 0;
    await tx(async (client) => {
      for (const [table, cols] of TABLES) {
        let rowsToCopy = [];
        try {
          rowsToCopy = sqlite.prepare(`SELECT ${cols.join(', ')} FROM ${table}`).all();
        } catch (e) {
          continue;
        }
        const placeholders = cols.map((_, i) => `$${i + 1}`).join(', ');
        const sql = `INSERT INTO ${table} (${cols.join(', ')}) VALUES (${placeholders}) ON CONFLICT DO NOTHING`;
        for (const row of rowsToCopy) {
          await client.query(sql, cols.map(c => row[c]));
          total++;
        }
      }
      for (const table of ['contacts', 'templates', 'campaigns', 'campaign_recipients']) {
        await client.query(
          `SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${table}), 0) + 1, false)`
        );
      }
      await client.query("INSERT INTO schema_meta (key, value) VALUES ('email_sqlite_migrated', $1) ON CONFLICT (key) DO NOTHING", [new Date().toISOString()]);
    });
    console.log(`  Email DB: migrated ${total} rows from legacy SQLite`);
  } finally {
    sqlite.close();
  }
}

// ─── Contacts ──────────────────────────────────────────────────────────────

export async function addContact({ email, name = '', tags = '' }) {
  return query(
    `INSERT INTO contacts (email, name, tags) VALUES ($1, $2, $3)
     ON CONFLICT (email) DO UPDATE SET name = excluded.name, tags = excluded.tags, updated_at = ${NOW}`,
    [email.toLowerCase().trim(), name.trim(), tags.trim()]
  );
}

export async function addContactsBulk(contacts) {
  return tx(async (client) => {
    let added = 0;
    for (const c of contacts) {
      if (c.email?.trim()) {
        await client.query(
          `INSERT INTO contacts (email, name, tags) VALUES ($1, $2, $3)
           ON CONFLICT (email) DO UPDATE SET name = excluded.name, tags = excluded.tags, updated_at = ${NOW}`,
          [c.email.toLowerCase().trim(), (c.name || '').trim(), (c.tags || '').trim()]
        );
        added++;
      }
    }
    return added;
  });
}

export async function getContacts({ subscribed } = {}) {
  if (subscribed !== undefined) {
    return rows('SELECT * FROM contacts WHERE subscribed = $1 ORDER BY created_at DESC', [subscribed ? 1 : 0]);
  }
  return rows('SELECT * FROM contacts ORDER BY created_at DESC');
}

export async function getContactById(id) {
  return one('SELECT * FROM contacts WHERE id = $1', [id]);
}

export async function deleteContact(id) {
  return query('DELETE FROM contacts WHERE id = $1', [id]);
}

export async function unsubscribeByTrackingId(trackingId) {
  const recipient = await one('SELECT contact_id FROM campaign_recipients WHERE tracking_id = $1', [trackingId]);
  if (recipient) {
    await query(`UPDATE contacts SET subscribed = 0, updated_at = ${NOW} WHERE id = $1`, [recipient.contact_id]);
    return true;
  }
  return false;
}

export async function toggleSubscription(contactId, subscribed) {
  return query(`UPDATE contacts SET subscribed = $1, updated_at = ${NOW} WHERE id = $2`, [subscribed ? 1 : 0, contactId]);
}

// ─── Templates ─────────────────────────────────────────────────────────────

export async function createTemplate({ name, subject, html_body }) {
  const row = await one('INSERT INTO templates (name, subject, html_body) VALUES ($1, $2, $3) RETURNING id', [name, subject, html_body]);
  return { lastInsertRowid: row.id };
}

export async function getTemplates() {
  return rows('SELECT * FROM templates ORDER BY updated_at DESC');
}

export async function getTemplateById(id) {
  return one('SELECT * FROM templates WHERE id = $1', [id]);
}

export async function updateTemplate(id, { name, subject, html_body }) {
  return query(`UPDATE templates SET name = $1, subject = $2, html_body = $3, updated_at = ${NOW} WHERE id = $4`, [name, subject, html_body, id]);
}

export async function deleteTemplate(id) {
  return query('DELETE FROM templates WHERE id = $1', [id]);
}

// ─── Campaigns ─────────────────────────────────────────────────────────────

export async function createCampaign({ name, subject, html_body, template_id }) {
  const row = await one('INSERT INTO campaigns (name, subject, html_body, template_id) VALUES ($1, $2, $3, $4) RETURNING id', [name, subject, html_body, template_id || null]);
  return { lastInsertRowid: row.id };
}

export async function getCampaigns() {
  return rows('SELECT * FROM campaigns ORDER BY created_at DESC');
}

export async function getCampaignById(id) {
  return one('SELECT * FROM campaigns WHERE id = $1', [id]);
}

export async function deleteCampaign(id) {
  return query('DELETE FROM campaigns WHERE id = $1', [id]);
}

export async function addCampaignRecipients(campaignId, contactIds, trackingIds) {
  return tx(async (client) => {
    for (let i = 0; i < contactIds.length; i++) {
      await client.query(
        'INSERT INTO campaign_recipients (campaign_id, contact_id, tracking_id) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING',
        [campaignId, contactIds[i], trackingIds[i]]
      );
    }
    await client.query('UPDATE campaigns SET total_recipients = $1 WHERE id = $2', [contactIds.length, campaignId]);
  });
}

export async function markCampaignSent(campaignId, sentCount) {
  return query(`UPDATE campaigns SET status = 'sent', sent_count = $1, sent_at = ${NOW} WHERE id = $2`, [sentCount, campaignId]);
}

export async function markRecipientSent(trackingId) {
  return query(`UPDATE campaign_recipients SET status = 'sent', sent_at = ${NOW} WHERE tracking_id = $1`, [trackingId]);
}

export async function recordOpen(trackingId) {
  const r = await one('SELECT * FROM campaign_recipients WHERE tracking_id = $1', [trackingId]);
  if (!r) return false;
  if (!r.opened) {
    await query(`UPDATE campaign_recipients SET opened = 1, opened_at = ${NOW} WHERE tracking_id = $1`, [trackingId]);
    await query('UPDATE campaigns SET open_count = open_count + 1 WHERE id = $1', [r.campaign_id]);
  }
  return true;
}

export async function recordClick(trackingId) {
  const r = await one('SELECT * FROM campaign_recipients WHERE tracking_id = $1', [trackingId]);
  if (!r) return false;
  if (!r.clicked) {
    await query(`UPDATE campaign_recipients SET clicked = 1, clicked_at = ${NOW} WHERE tracking_id = $1`, [trackingId]);
    await query('UPDATE campaigns SET click_count = click_count + 1 WHERE id = $1', [r.campaign_id]);
  }
  return true;
}

export async function getCampaignRecipients(campaignId) {
  return rows(
    `SELECT cr.*, c.email, c.name, c.subscribed
     FROM campaign_recipients cr
     JOIN contacts c ON cr.contact_id = c.id
     WHERE cr.campaign_id = $1
     ORDER BY cr.opened DESC, cr.sent_at DESC`,
    [campaignId]
  );
}

export async function getAnalytics() {
  const totalContacts = (await one('SELECT COUNT(*)::int as count FROM contacts')).count;
  const subscribedContacts = (await one('SELECT COUNT(*)::int as count FROM contacts WHERE subscribed = 1')).count;
  const totalCampaigns = (await one("SELECT COUNT(*)::int as count FROM campaigns WHERE status = 'sent'")).count;
  const totalSent = (await one('SELECT COALESCE(SUM(sent_count), 0)::int as total FROM campaigns')).total;
  const totalOpens = (await one('SELECT COALESCE(SUM(open_count), 0)::int as total FROM campaigns')).total;
  const recentCampaigns = await rows("SELECT * FROM campaigns WHERE status = 'sent' ORDER BY sent_at DESC LIMIT 10");
  return { totalContacts, subscribedContacts, totalCampaigns, totalSent, totalOpens, recentCampaigns };
}

export default pool;
